### ISSUE TITLE
 Unsupported record size:52

### ISSUE THREAD

**Issue by twakeman-giti** [chrispassas/silk#3]
I have flow files that do not parse because the record size is not one of the 3 file sizes supported. I would like to help make this available. I found the information. I will work on it and submit a PR

**Comment by chrispassas** [comment]
Some of the information I got here:
https://tools.netsa.cert.org/silk/faq.html#file-formats

Also I downloaded the source code and tried my best to read it:
https://tools.netsa.cert.org/silk/download.html#

Also did spent some time just writing Go code to explore reading the files. I used the silk tools to help test if my code was reading correctly.

I would print out file content with rwfilter | rwcut then output from my code and compare if they matched.

Besides looking at the silk code I mostly found code comments to be the most useful.

**Comment by twakeman-giti** [comment]
Thank you
